version: '2'
services:
  app:
    build: .
    command: sh ./script/start.sh
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - "80:3000"

  db:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions

volumes:
  bundle: {}
